# This is a basic workflow to help you get started with Actions

name: first-workflow

# Controls when the workflow will run
on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        # You may pin to the exact commit or the version.
        # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
        uses: mscoutermarsh/cowsays-action@v1
        with:
       # What does the cow say?
          text: Moooo
       # Color of your cow
          color: white
          
